name: Deploy to Server

on:
  push:
    branches:
      - main  # only deploy on production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (optional)
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Git Pull on Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/root/website/blog-admin/
            git pull
            npm i
            npm run build
            cd server/
            npm i
            pm2 restart blog-admin || pm2 restart blog-admin-api
EOF
